version: '3.8'

services:
  naka-chan:
    container_name: naka_chan
    environment:
      USER: naka_chan
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    build: 
      context: .
      dockerfile: ./docker/naka-chan/Dockerfile
    image: rust:1.55-slim
    command: cd /app && cargo run
    ports: 
      - 8080:80
  naka-chan-develop:
    build: 
      context: .
      dockerfile: ./docker/naka-chan-develop/Dockerfile
    container_name: naka_chan_develop
    environment:
      USER: naka_chan
      DISCORD_TOKEN: ${DISCORD_TOKEN_DEV}
    ports: 
      - 8081:80
